/**
 * Tool Maintenance Web Application - Core Dataset
 * Extracted and enriched from GP-CoS - LAIR Preparation & Tool Maintenance Specifications
 */

const INITIAL_DATA = {
    tools: [
        {
            id: "TL-001",
            partNumber: "S1A28862",
            description: "Terminal plug-in low rating",
            criticality: "MAJOR",
            category: "Electrical Terminals",
            toolId: "DIE-TRM-8862-A",
            toolType: "Progressive Stamping Die",
            pressTonnage: "110T Komatsu",
            material: "Copper Alloy C1100 / Silver Inlay",
            cavities: 2,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received at JR-TH; QA dimensional approval in progress",
            image: "images/image11.png",
            strokesCurrent: 85400,
            strokesMax: 250000,
            pmIntervalStrokes: 50000,
            lastPmDate: "2026-08-20",
            nextPmDate: "2026-10-15",
            healthStatus: "Operational",
            location: "Bay 2 - Press Line P03",
            assignedTech: "R. Sudhakar",
            notes: "Silver plating contact area requires surface profile roughness test Ra < 0.4µm."
        },
        {
            id: "TL-002",
            partNumber: "S1A28863",
            description: "Terminal plug-in high rating",
            criticality: "MAJOR",
            category: "Electrical Terminals",
            toolId: "DIE-TRM-8863-B",
            toolType: "Progressive Stamping Die",
            pressTonnage: "160T Aida",
            material: "Electrolytic Copper E-Cu58 / Silver Plated",
            cavities: 2,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; high rating thermal rise test planned",
            image: "images/image10.png",
            strokesCurrent: 112000,
            strokesMax: 250000,
            pmIntervalStrokes: 50000,
            lastPmDate: "2026-08-22",
            nextPmDate: "2026-10-18",
            healthStatus: "Operational",
            location: "Bay 2 - Press Line P04",
            assignedTech: "T. Narong",
            notes: "Heavier gauge terminal stock (2.5mm). Monitor punch wear radius closely."
        },
        {
            id: "TL-003",
            partNumber: "GHJ16013AA",
            description: "Spreader1 4P",
            criticality: "MINOR",
            category: "Insulation & Spreaders",
            toolId: "MLD-SPR-6013-1",
            toolType: "Precision Stamping Die",
            pressTonnage: "80T Chin Fong",
            material: "High Dielectric Phosphor Bronze",
            cavities: 4,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; form profile meets drawing rev 03",
            image: "images/image8.png",
            strokesCurrent: 145000,
            strokesMax: 400000,
            pmIntervalStrokes: 75000,
            lastPmDate: "2026-08-15",
            nextPmDate: "2026-11-01",
            healthStatus: "Operational",
            location: "Bay 1 - Press Line P01",
            assignedTech: "K. Somchai",
            notes: "4-pole configuration spreader. Check guide pillar alignment on stripper."
        },
        {
            id: "TL-004",
            partNumber: "GHJ16016AA",
            description: "Spreader4 4P",
            criticality: "MINOR",
            category: "Insulation & Spreaders",
            toolId: "MLD-SPR-6016-4",
            toolType: "Precision Stamping Die",
            pressTonnage: "80T Chin Fong",
            material: "Phosphor Bronze CuSn6",
            cavities: 4,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; fitment check passed on prototype housing",
            image: "images/image6.png",
            strokesCurrent: 162000,
            strokesMax: 400000,
            pmIntervalStrokes: 75000,
            lastPmDate: "2026-08-16",
            nextPmDate: "2026-11-05",
            healthStatus: "Operational",
            location: "Bay 1 - Press Line P01",
            assignedTech: "K. Somchai",
            notes: "Bending die insert polished during last maintenance."
        },
        {
            id: "TL-005",
            partNumber: "GHJ16014AA",
            description: "Spreader2 4P",
            criticality: "MINOR",
            category: "Insulation & Spreaders",
            toolId: "MLD-SPR-6014-2",
            toolType: "Precision Stamping Die",
            pressTonnage: "80T Chin Fong",
            material: "Phosphor Bronze CuSn6",
            cavities: 4,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; batch samples within tolerance",
            image: "images/image9.png",
            strokesCurrent: 138000,
            strokesMax: 400000,
            pmIntervalStrokes: 75000,
            lastPmDate: "2026-08-18",
            nextPmDate: "2026-11-02",
            healthStatus: "Operational",
            location: "Bay 1 - Press Line P02",
            assignedTech: "A. Wongso",
            notes: "Good tool condition. Ejector pins lubricated with synthetic ISO VG 68."
        },
        {
            id: "TL-006",
            partNumber: "GHJ16015AA",
            description: "Spreader3 4P",
            criticality: "MINOR",
            category: "Insulation & Spreaders",
            toolId: "MLD-SPR-6015-3",
            toolType: "Precision Stamping Die",
            pressTonnage: "80T Chin Fong",
            material: "Phosphor Bronze CuSn6",
            cavities: 4,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; no burrs detected on trimmed edges",
            image: "images/image7.png",
            strokesCurrent: 156000,
            strokesMax: 400000,
            pmIntervalStrokes: 75000,
            lastPmDate: "2026-08-19",
            nextPmDate: "2026-11-04",
            healthStatus: "Operational",
            location: "Bay 1 - Press Line P02",
            assignedTech: "A. Wongso",
            notes: "Cutting edge reground at 100k strokes. Clearance checked at 0.04mm."
        },
        {
            id: "TL-007",
            partNumber: "48187114AA",
            description: "PLATE, SLIDE",
            criticality: "MINOR",
            category: "Kinematic Plates",
            toolId: "DIE-PLT-7114",
            toolType: "Compound Piercing & Blanking Die",
            pressTonnage: "160T Aida",
            material: "Cold Rolled Steel SPCC Hardened",
            cavities: 1,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Finished Trial and Sample Submission",
            image: "images/image13.png",
            strokesCurrent: 242000,
            strokesMax: 300000,
            pmIntervalStrokes: 60000,
            lastPmDate: "2026-08-28",
            nextPmDate: "2026-10-10",
            healthStatus: "Inspection Due",
            location: "Bay 3 - Press Line P05",
            assignedTech: "R. Sudhakar",
            notes: "Strokes reaching 80% of life limit. Plan tool re-sharpening and slide gap calibration."
        },
        {
            id: "TL-008",
            partNumber: "48187099AA",
            description: "PLATE, CAM",
            criticality: "MINOR",
            category: "Kinematic Plates",
            toolId: "DIE-CAM-7099",
            toolType: "Fine Blanking Die",
            pressTonnage: "160T Aida",
            material: "Carbon Steel S45C Induction Hardened",
            cavities: 1,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; profile contour CMM scanned with 100% compliance",
            image: "images/image4.png",
            strokesCurrent: 188000,
            strokesMax: 300000,
            pmIntervalStrokes: 60000,
            lastPmDate: "2026-08-25",
            nextPmDate: "2026-10-25",
            healthStatus: "Operational",
            location: "Bay 3 - Press Line P05",
            assignedTech: "T. Narong",
            notes: "Cam profile contour critical for trip mechanism actuation."
        },
        {
            id: "TL-009",
            partNumber: "48187081AA",
            description: "CLAMP, SHAFT",
            criticality: "CRITICAL",
            category: "Shaft & Mechanism Locking",
            toolId: "DIE-CLP-7081-CRIT",
            toolType: "High Precision Multi-Stage Die",
            pressTonnage: "200T Komatsu",
            material: "Alloy Steel AISI 4140 Quenched & Tempered",
            cavities: 2,
            samplesQty: 30,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; critical bore roundness verification in progress",
            image: "images/image5.png",
            strokesCurrent: 184500,
            strokesMax: 200000,
            pmIntervalStrokes: 40000,
            lastPmDate: "2026-09-01",
            nextPmDate: "2026-10-08",
            healthStatus: "Maintenance Due",
            location: "Bay 4 - Precision Press P07",
            assignedTech: "R. Sudhakar",
            notes: "CRITICAL: Clamping torque relies on inner ear radius. Tool nearing PM threshold."
        },
        {
            id: "TL-010",
            partNumber: "48187077AA",
            description: "LEVER, DOOR LOCK",
            criticality: "CRITICAL",
            category: "Safety Interlocks",
            toolId: "DIE-LVR-7077-CRIT",
            toolType: "Multi-Cavity Stamping & Forming Die",
            pressTonnage: "110T Komatsu",
            material: "Stainless Steel SUS304 Full Hard",
            cavities: 2,
            samplesQty: 30,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; door interlock functional safety testing passed",
            image: "images/image2.png",
            strokesCurrent: 173000,
            strokesMax: 200000,
            pmIntervalStrokes: 40000,
            lastPmDate: "2026-09-02",
            nextPmDate: "2026-10-12",
            healthStatus: "Operational",
            location: "Bay 4 - Precision Press P08",
            assignedTech: "K. Somchai",
            notes: "Safety lock lever. Bending radius R=1.2 ± 0.05mm must be inspected every 5,000 strokes."
        },
        {
            id: "TL-011",
            partNumber: "48187083AA",
            description: "STRIKER-PLATE",
            criticality: "MINOR",
            category: "Kinematic Plates",
            toolId: "DIE-STK-7083",
            toolType: "Heavy Duty Piercing Die",
            pressTonnage: "160T Aida",
            material: "Spring Steel SK5 Tempered HRC 44-48",
            cavities: 2,
            samplesQty: 10,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; hardness verification HRC 46 achieved",
            image: "images/image3.png",
            strokesCurrent: 94000,
            strokesMax: 350000,
            pmIntervalStrokes: 60000,
            lastPmDate: "2026-08-30",
            nextPmDate: "2026-11-20",
            healthStatus: "Operational",
            location: "Bay 3 - Press Line P06",
            assignedTech: "A. Wongso",
            notes: "Impact face wear minimal. Guide pillars in good condition."
        },
        {
            id: "TL-012",
            partNumber: "48187082AA",
            description: "LOCK, SHAFT",
            criticality: "CRITICAL",
            category: "Shaft & Mechanism Locking",
            toolId: "DIE-LCK-7082-CRIT",
            toolType: "Multi-Stage Carbide Insert Die",
            pressTonnage: "200T Komatsu",
            material: "Case Hardened Steel 20MnCr5",
            cavities: 1,
            samplesQty: 30,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Samples received; critical latch tooth profile approved",
            image: "images/image1.png",
            strokesCurrent: 196200,
            strokesMax: 200000,
            pmIntervalStrokes: 40000,
            lastPmDate: "2026-08-10",
            nextPmDate: "2026-10-07",
            healthStatus: "Critical Attention",
            location: "Bay 4 - Precision Press P07",
            assignedTech: "R. Sudhakar",
            notes: "URGENT: Current stroke 196,200 of 200,000 max. Carbide punch regrinding overdue."
        },
        {
            id: "TL-013",
            partNumber: "48187087AA",
            description: "LEVER, SHAFT RELEASE",
            criticality: "CRITICAL",
            category: "Shaft & Mechanism Locking",
            toolId: "DIE-REL-7087-CRIT",
            toolType: "Progressive Forming & Coin Die",
            pressTonnage: "160T Aida",
            material: "High Tensile Steel SCM435",
            cavities: 2,
            samplesQty: 30,
            pipelineStatus: "Sent to JR-TH",
            statusDate: "2026-09-03",
            remarks: "Finished Trial and Sample Submission",
            image: "images/image12.png",
            strokesCurrent: 167500,
            strokesMax: 200000,
            pmIntervalStrokes: 40000,
            lastPmDate: "2026-08-29",
            nextPmDate: "2026-10-20",
            healthStatus: "Operational",
            location: "Bay 4 - Precision Press P08",
            assignedTech: "T. Narong",
            notes: "Trial run successfully completed. Samples approved by JR-TH engineering team."
        },
        {
            id: "TL-014",
            partNumber: "48187076AA",
            description: "LATCH, UVR",
            criticality: "CRITICAL",
            category: "Under-Voltage Mechanism",
            toolId: "DIE-UVR-7076-CRIT",
            toolType: "Precision Stamping & Bending Die",
            pressTonnage: "110T Komatsu",
            material: "Stainless Steel SUS420J2 Hardened",
            cavities: 2,
            samplesQty: 30,
            pipelineStatus: "Samples Preparation in progress",
            statusDate: "2026-09-12",
            remarks: "Finished Trial and Sample Submission; preparing secondary batch",
            image: "images/image14.png",
            strokesCurrent: 44800,
            strokesMax: 150000,
            pmIntervalStrokes: 30000,
            lastPmDate: "2026-09-10",
            nextPmDate: "2026-10-24",
            healthStatus: "Trial In Progress",
            location: "Toolroom Prototype Cell",
            assignedTech: "R. Sudhakar",
            notes: "UVR latch trip torque calibration required. Tool punch angle adjusted +0.2 deg."
        },
        {
            id: "TL-015",
            partNumber: "S1B22575",
            description: "TERMINAL Connection(with SILVER TIP)",
            criticality: "MAJOR",
            category: "Electrical Terminals",
            toolId: "DIE-TRM-2575-ST",
            toolType: "Silver Tip Resistance Braze & Stamping Die",
            pressTonnage: "110T Komatsu",
            material: "Cu-ETP Copper + AgNi0.15 Contact Tip",
            cavities: 1,
            samplesQty: 10,
            pipelineStatus: "Samples Preparation in progress",
            statusDate: "2026-09-18",
            remarks: "Samples not yet Received; die braze station tooling undergoing alignment",
            image: "images/image11.png",
            strokesCurrent: 31200,
            strokesMax: 200000,
            pmIntervalStrokes: 40000,
            lastPmDate: "2026-09-05",
            nextPmDate: "2026-10-30",
            healthStatus: "Pipeline Pending",
            location: "Bay 2 - Press Line P03",
            assignedTech: "T. Narong",
            notes: "Silver tip alignment fixture checked. Awaiting sample delivery."
        },
        {
            id: "TL-016",
            partNumber: "S1B22372",
            description: "TERMINAL Connection(W/O SILVER TIP)",
            criticality: "MAJOR",
            category: "Electrical Terminals",
            toolId: "DIE-TRM-2372-WO",
            toolType: "High Speed Blanking & Piercing Die",
            pressTonnage: "110T Komatsu",
            material: "High Conductivity Copper C11000",
            cavities: 2,
            samplesQty: 10,
            pipelineStatus: "Samples Preparation in progress",
            statusDate: "2026-09-18",
            remarks: "Samples not yet Received; strip feed guide adjusted for burr elimination",
            image: "images/image10.png",
            strokesCurrent: 33400,
            strokesMax: 250000,
            pmIntervalStrokes: 50000,
            lastPmDate: "2026-09-08",
            nextPmDate: "2026-11-05",
            healthStatus: "Pipeline Pending",
            location: "Bay 2 - Press Line P04",
            assignedTech: "K. Somchai",
            notes: "Strip pitch feed calibration completed. Tool ready for next sample run."
        },
        {
            id: "TL-017",
            partNumber: "S1A23987",
            description: "ARC STACK LOW",
            criticality: "CRITICAL",
            category: "Arc Chutes & De-ion Plates",
            toolId: "DIE-ARC-3987-CRIT",
            toolType: "Multi-De-ion Plate Interlock Die",
            pressTonnage: "160T Aida",
            material: "Low Carbon Steel SPCC Nickel Plated",
            cavities: 4,
            samplesQty: 30,
            pipelineStatus: "Samples Preparation in progress",
            statusDate: "2026-09-20",
            remarks: "Samples not yet Received; de-ion plate slot clearance fine-tuning",
            image: "images/image4.png",
            strokesCurrent: 28900,
            strokesMax: 180000,
            pmIntervalStrokes: 35000,
            lastPmDate: "2026-09-12",
            nextPmDate: "2026-10-28",
            healthStatus: "Pipeline Pending",
            location: "Bay 3 - Press Line P06",
            assignedTech: "R. Sudhakar",
            notes: "CRITICAL: Arc extinguishing stack geometry. Check slot nesting tolerance."
        },
        {
            id: "TL-018",
            partNumber: "48187145AA",
            description: "STAPLE",
            criticality: "CRITICAL",
            category: "Retaining Staples & Hardware",
            toolId: "DIE-STP-7145-CRIT",
            toolType: "Wire Forming & Cut-Off Tool",
            pressTonnage: "60T Bihler Multi-Slide",
            material: "Spring Steel Wire SWPB Ø1.8mm",
            cavities: 2,
            samplesQty: 30,
            pipelineStatus: "Samples Preparation in progress",
            statusDate: "2026-09-22",
            remarks: "Samples not yet Received; mandrel radius tooling re-polished",
            image: "images/image13.png",
            strokesCurrent: 35600,
            strokesMax: 220000,
            pmIntervalStrokes: 45000,
            lastPmDate: "2026-09-14",
            nextPmDate: "2026-11-10",
            healthStatus: "Pipeline Pending",
            location: "Bay 1 - Wire Forming Cell W01",
            assignedTech: "A. Wongso",
            notes: "CRITICAL: Retaining staple holding force. Monitor wire feed tension roller wear."
        }
    ],

    workOrders: [
        {
            id: "WO-2026-089",
            toolId: "DIE-LCK-7082-CRIT",
            partNumber: "48187082AA",
            partDescription: "LOCK, SHAFT",
            orderType: "Corrective Maintenance (CM)",
            priority: "URGENT",
            status: "In Progress",
            createdDate: "2026-10-05",
            dueDate: "2026-10-07",
            assignedTech: "R. Sudhakar",
            strokesAtMaintenance: 196200,
            problemDescription: "Carbide punch edge chipping detected during optical inspection. Stroke count is at 98.1% of maximum service life.",
            actionPlan: "Dismantle die block upper station. Regrind punch face 0.15mm on surface grinder. Replace stripper springs and test stroke.",
            checklist: [
                { task: "Visual crack & chip check on carbide punch inserts", done: true },
                { task: "Clean & demagnetize die components", done: true },
                { task: "Precision surface grind punch cutting edges", done: false },
                { task: "Measure cutting clearance (target 0.035 ± 0.005mm)", done: false },
                { task: "Replace heavy duty stripper die springs (x4)", done: false },
                { task: "Trial stroke & first-off dimensional CMM check", done: false }
            ],
            notes: "Spare carbide punch insert is in Toolroom Cabinet B, Shelf 3."
        },
        {
            id: "WO-2026-088",
            toolId: "DIE-CLP-7081-CRIT",
            partNumber: "48187081AA",
            partDescription: "CLAMP, SHAFT",
            orderType: "Preventive Maintenance (PM)",
            priority: "HIGH",
            status: "Scheduled",
            createdDate: "2026-10-04",
            dueDate: "2026-10-08",
            assignedTech: "T. Narong",
            strokesAtMaintenance: 184500,
            problemDescription: "Scheduled 40k stroke PM due. Critical clamp ear clamping force audit required for LAIR sign-off.",
            actionPlan: "Standard 40k PM checklist. Clean guide pins, ultrasonic clean cavity blocks, inspect guide bushing play, lubricate with high-pressure grease.",
            checklist: [
                { task: "Disassemble upper and lower die sets", done: false },
                { task: "Inspect guide pillars & ball cages for radial play", done: false },
                { task: "Inspect clamp radius forming punch for galling", done: false },
                { task: "Re-torque all die shoe fastening bolts to 85 N-m", done: false },
                { task: "Apply synthetic extreme-pressure grease", done: false },
                { task: "Run 20 dry cycles and record tonnage pressure", done: false }
            ],
            notes: "Coordinate with Production Supervisor before taking Press Line P07 offline."
        },
        {
            id: "WO-2026-087",
            toolId: "DIE-PLT-7114",
            partNumber: "48187114AA",
            partDescription: "PLATE, SLIDE",
            orderType: "Preventive Maintenance (PM)",
            priority: "MEDIUM",
            status: "Scheduled",
            createdDate: "2026-10-03",
            dueDate: "2026-10-10",
            assignedTech: "K. Somchai",
            strokesAtMaintenance: 242000,
            problemDescription: "60k interval maintenance. Burr height on blanking edge approaching 0.05mm max threshold.",
            actionPlan: "Sharpen blanking punch and die plate. Deburr stripper plate slots.",
            checklist: [
                { task: "Inspect blanking perimeter for edge wear", done: false },
                { task: "Surface grind die plate 0.10mm", done: false },
                { task: "Check slide guide clearance", done: false },
                { task: "Lubricate guide pillars", done: false }
            ],
            notes: "Trial samples were submitted and approved by JR-TH."
        },
        {
            id: "WO-2026-085",
            toolId: "DIE-UVR-7076-CRIT",
            partNumber: "48187076AA",
            partDescription: "LATCH, UVR",
            orderType: "Trial Tooling Modification",
            priority: "HIGH",
            status: "Completed",
            createdDate: "2026-09-08",
            dueDate: "2026-09-11",
            assignedTech: "R. Sudhakar",
            strokesAtMaintenance: 44800,
            problemDescription: "LAIR trial feedback requested +0.2° adjustment on final latch hook bend to ensure 100% trip reliability.",
            actionPlan: "Modify CNC bending insert angle from 89.8° to 90.0°. Polish contact radius to Ra 0.2µm.",
            checklist: [
                { task: "EDM wire cut new bending insert with compensated angle", done: true },
                { task: "Hand polish latch contact radius", done: true },
                { task: "Install insert into station 5 of progressive die", done: true },
                { task: "Run 30 trial samples for JR-TH submission", done: true },
                { task: "Quality sign-off on trip angle and pull force", done: true }
            ],
            notes: "Successfully completed. 30 samples submitted for JR-TH trial review."
        }
    ],

    maintenanceHistory: [
        {
            id: "HIST-2026-042",
            date: "2026-09-12",
            toolId: "DIE-ARC-3987-CRIT",
            partNumber: "S1A23987",
            partDescription: "ARC STACK LOW",
            type: "Preventive Maintenance",
            tech: "R. Sudhakar",
            strokes: 28900,
            downtimeHours: 3.5,
            actions: "Cleaned de-ion stacking chute. Polished piercing punches. Lubricated sliding guides.",
            outcome: "Passed inspection. Zero burr measured."
        },
        {
            id: "HIST-2026-041",
            date: "2026-09-10",
            toolId: "DIE-UVR-7076-CRIT",
            partNumber: "48187076AA",
            partDescription: "LATCH, UVR",
            type: "Tool Modification",
            tech: "R. Sudhakar",
            strokes: 44800,
            downtimeHours: 6.0,
            actions: "Modified station 5 bending punch for +0.2 deg compensation. Trial samples pressed.",
            outcome: "Samples approved for JR-TH trial."
        },
        {
            id: "HIST-2026-040",
            date: "2026-09-02",
            toolId: "DIE-LVR-7077-CRIT",
            partNumber: "48187077AA",
            partDescription: "LEVER, DOOR LOCK",
            type: "Preventive Maintenance",
            tech: "K. Somchai",
            strokes: 173000,
            downtimeHours: 4.0,
            actions: "40k stroke PM. Inspected lever pivot holes. Replaced 2 stripper springs. Grease applied.",
            outcome: "Certified operational."
        },
        {
            id: "HIST-2026-039",
            date: "2026-09-01",
            toolId: "DIE-CLP-7081-CRIT",
            partNumber: "48187081AA",
            partDescription: "CLAMP, SHAFT",
            type: "Routine Inspection",
            tech: "R. Sudhakar",
            strokes: 184500,
            downtimeHours: 2.0,
            actions: "Cleaned stamping dies. Visual check on clamp ears. Scheduled upcoming comprehensive PM.",
            outcome: "Operational with PM work order created."
        },
        {
            id: "HIST-2026-038",
            date: "2026-08-30",
            toolId: "DIE-STK-7083",
            partNumber: "48187083AA",
            partDescription: "STRIKER-PLATE",
            type: "Preventive Maintenance",
            tech: "A. Wongso",
            strokes: 94000,
            downtimeHours: 3.0,
            actions: "Surface ground cutting edge 0.08mm. Cleaned stripper pad. Lubricated pins.",
            outcome: "Burr height reduced to 0.012mm."
        },
        {
            id: "HIST-2026-037",
            date: "2026-08-28",
            toolId: "DIE-PLT-7114",
            partNumber: "48187114AA",
            partDescription: "PLATE, SLIDE",
            type: "Preventive Maintenance",
            tech: "R. Sudhakar",
            strokes: 242000,
            downtimeHours: 4.5,
            actions: "Full clean & lube. Measured guide bushing play (0.015mm, within tolerance).",
            outcome: "Operational."
        },
        {
            id: "HIST-2026-036",
            date: "2026-08-22",
            toolId: "DIE-TRM-8863-B",
            partNumber: "S1A28863",
            partDescription: "Terminal plug-in high rating",
            type: "Preventive Maintenance",
            tech: "T. Narong",
            strokes: 112000,
            downtimeHours: 4.0,
            actions: "50k PM service. Polished silver plating contact formers. Calibrated feed pitch.",
            outcome: "Certified operational."
        },
        {
            id: "HIST-2026-035",
            date: "2026-08-20",
            toolId: "DIE-TRM-8862-A",
            partNumber: "S1A28862",
            partDescription: "Terminal plug-in low rating",
            type: "Preventive Maintenance",
            tech: "R. Sudhakar",
            strokes: 85400,
            downtimeHours: 3.8,
            actions: "50k PM service. Ultrasonic cleaned punch assemblies. Checked clearance.",
            outcome: "Certified operational."
        }
    ],

    standardChecklistTemplates: [
        "Visual crack, chip & galling inspection on punches and die inserts",
        "Clean, demagnetize & remove accumulated metal swarf/slugs",
        "Inspect guide pillars, ball cages & bushings for radial play & wear",
        "Measure cutting & blanking clearances against engineering tolerance",
        "Inspect stripper plate, ejector pins & test die spring tension",
        "Check nitrogen cylinder pressure / mechanical spring fatigue",
        "Verify pilot pin alignment and stock feeder pitch accuracy",
        "Perform precision lubrication with specified ISO grade synthetic lubricant",
        "Run 10 trial strokes and inspect first-off part dimensions on CMM/profile projector",
        "Record stroke counter, attach inspection record & sign off maintenance log"
    ]
};

// Export for browser and node/powershell environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = INITIAL_DATA;
}
